identityserver:
    container_name: identityserver
    build: ./GoFish.Identity
    ports:
      - "5000:5000"

api:
    container_name: api
    build: ./GoFish.Advert
    ports:
      - "5001:5001"
    links:
      - identityserver:localhost

client:
    container_name: client
    build: ./GoFish.UI.MVC
    ports:
      - "5003:5003"
    links:
      - identityserver:localhost
      - api

eventstore:
    container_name: eventstore
    image: eventstore/eventstore
    ports:
     - "1113:1113"
     - "2113:2113"