identity:
    container_name: gofish_identity
    build: ./GoFish.Identity
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT

advert_api:
    container_name: gofish_advert_api
    build: ./GoFish.Api/GoFish.Advert
    ports:
      - "5001:5001"
    links:
      - identity:localhost
    environment:
      - ASPNETCORE_ENVIRONMENT

inventory_api:
    container_name: gofish_inventory_api
    build: ./GoFish.Api/GoFish.Inventory
    ports:
      - "5002:5002"
    links:
      - identity:localhost
    environment:
      - ASPNETCORE_ENVIRONMENT

ui_mvc_advert:
    container_name: gofish_ui_mvc_advert
    build: ./GoFish.UI/GoFish.UI.MVC/GoFish.UI.MVC.Advert
    ports:
      - "5003:5003"
    links:
      - identity:localhost
    environment:
      - ASPNETCORE_ENVIRONMENT

ui_mvc_dashboard:
    container_name: gofish_ui_mvc_dashboard
    build: ./GoFish.UI/GoFish.UI.MVC/GoFish.UI.MVC.Dashboard
    ports:
      - "5005:5005"
    links:
      - identity:localhost
    environment:
      - ASPNETCORE_ENVIRONMENT

inventory_receiver:
    container_name: gofish_inventory_receiver
    build: ./GoFish.Api/GoFish.Inventory.Receiver
    tty: true
    links:
      - identity:localhost
    environment:
      - ASPNETCORE_ENVIRONMENT

advert_receiver:
    container_name: gofish_advert_receiver
    build: ./GoFish.Api/GoFish.Advert.Receiver
    tty: true
    links:
      - identity:localhost
    environment:
      - ASPNETCORE_ENVIRONMENT

eventstore:
    container_name: eventstore
    image: eventstore/eventstore
    ports:
     - "1113:1113"
     - "2113:2113"