identity:
    container_name: gofish_identity
    build: ./GoFish.Identity
    ports:
      - "5000:5000"

advert_api:
    container_name: gofish_advert_api
    build: ./GoFish.Advert
    ports:
      - "5001:5001"
    links:
      - identity:localhost

ui_mvc:
    container_name: gofish_ui_mvc
    build: ./GoFish.UI.MVC
    ports:
      - "5003:5003"
    links:
      - identity:localhost
      - advert_api

eventstore:
    container_name: eventstore
    image: eventstore/eventstore
    ports:
     - "1113:1113"
     - "2113:2113"